#!/bin/bash

echo "🚀 Accès à Grafana pour les métriques DevOps Project"
echo "=================================================="
echo ""
echo "📊 Grafana Dashboard:"
echo "   URL: http://localhost:3000"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "📈 Prometheus:"
echo "   URL: http://localhost:9090"
echo ""
echo "🔍 cAdvisor (métriques conteneurs):"
echo "   URL: http://localhost:8080"
echo ""
echo "📋 Conteneurs DevOps surveillés:"
echo "   - idurar-frontend (Port 3002)"
echo "   - idurar-backend (Port 5001)"
echo "   - idurar-mongodb (Port 27017)"
echo "   - idurar-portainer (Port 9000)"
echo ""
echo "🎯 Dashboard recommandé: 'DevOps Project - Conteneurs Non-Optimisés (Live)'"
echo ""
echo "💡 Pour importer le dashboard:"
echo "   1. Ouvrir Grafana: http://localhost:3000"
echo "   2. Se connecter avec admin/admin123"
echo "   3. Aller dans 'Dashboards' > 'DevOps Project'"
echo "   4. Sélectionner 'DevOps Project - Conteneurs Non-Optimisés (Live)'"
echo ""
echo "🔄 Redémarrage des services de monitoring..."
docker restart grafana-non-optimized prometheus-non-optimized cadvisor-non-optimized
echo "✅ Services redémarrés!"
echo ""
echo "🌐 Ouverture de Grafana dans le navigateur..."
sleep 3
open http://localhost:3000 2>/dev/null || xdg-open http://localhost:3000 2>/dev/null || echo "Veuillez ouvrir http://localhost:3000 dans votre navigateur"
