version: '3.8'

services:
  # Grafana pour version non-optimisée
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-non-optimized
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - monitoring-network
      - idurar-network  # Connecter au réseau de l'app non-optimisée

  # Prometheus pour collecter les métriques
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-non-optimized
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-non-optimized.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring-network
      - idurar-network

  # cAdvisor pour les métriques des conteneurs
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-non-optimized
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    command:
      - '--port=8080'
      - '--housekeeping_interval=5s'
      - '--docker_only=true'
      - '--store_container_labels=true'
      - '--whitelisted_container_labels=name'
    networks:
      - monitoring-network
      - idurar-network

  # Node Exporter pour les métriques système
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-non-optimized
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    privileged: true
    networks:
      - monitoring-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring-network:
    driver: bridge
  idurar-network:
    external: true  # Utiliser le réseau existant de l'app non-optimisée
