global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  # Jenkins Energy Metrics Exporter
  - job_name: 'jenkins-energy-exporter'
    static_configs:
      - targets: ['jenkins-energy-exporter:9091']
    scrape_interval: 15s
    metrics_path: /metrics


  # Energy Collector
  - job_name: 'energy-collector'
    static_configs:
      - targets: ['energy-collector:9094']
    scrape_interval: 30s
    metrics_path: /metrics

  # Jenkins with Prometheus plugin
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
    scrape_interval: 30s
    metrics_path: /prometheus
    basic_auth:
      username: 'admin'
      password: 'admin'

  # System energy monitoring
  - job_name: 'system-energy'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - systemd


