version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-network
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jenkins-network
      - idurar-network

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
  idurar-network:
    external: true
