services:
  # Jenkins Master - Simplified
  jenkins:
    image: jenkins/jenkins:lts
    container_name: idurar-jenkins-simple
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

  # Test Database
  jenkins-mongodb:
    image: mongo:7.0
    container_name: jenkins-mongodb-simple
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jenkins
      MONGO_INITDB_ROOT_PASSWORD: jenkins123
      MONGO_INITDB_DATABASE: jenkins_test
    volumes:
      - jenkins_mongodb_data:/data/db
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  jenkins_mongodb_data:

networks:
  jenkins-network:
    driver: bridge
