version: '3.8'

services:
  # Jenkins Master
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idurar-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

  # Jenkins Agent for heavy testing
  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: idurar-jenkins-agent
    restart: unless-stopped
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=jenkins-secret
      - JENKINS_AGENT_NAME=heavy-test-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace
    depends_on:
      - jenkins
    networks:
      - jenkins-network

  # Test Database for Jenkins
  jenkins-mongodb:
    image: mongo:7.0
    container_name: jenkins-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jenkins
      MONGO_INITDB_ROOT_PASSWORD: jenkins123
      MONGO_INITDB_DATABASE: jenkins_test
    volumes:
      - jenkins_mongodb_data:/data/db
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  jenkins_mongodb_data:

networks:
  jenkins-network:
    driver: bridge
