version: '3.8'

services:
  jenkins-fast:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-fast
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080 --prefix=/jenkins
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=100
    volumes:
      - jenkins_home_fast:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - jenkins-fast
    # Optimisations pour démarrage rapide
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # MongoDB pour les tests
  mongodb-test:
    image: mongo:7.0
    container_name: mongodb-test
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data_test:/data/db
    networks:
      - jenkins-fast

volumes:
  jenkins_home_fast:
  mongodb_data_test:

networks:
  jenkins-fast:
    driver: bridge
