services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-optimized
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ../:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx1024m -Xms512m
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network

  # Test Database - Lighter
  test-mongodb:
    image: mongo:7.0
    container_name: test-mongodb
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - test_mongodb_data:/data/db
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  test_mongodb_data:

networks:
  jenkins-network:
    driver: bridge
